default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: unicode
  database: database_all
  username: tawataka

test:
  <<: *default
  encoding: unicode
  database: database_test
  username: tawataka

production:
  <<: *default